apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/Susan-hue/go-web-app.git
    targetRevision: main
    path: argocd-apps/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true